services:
    frontend:
        container_name: app_frontend
        build: ./frontend
        ports:
            - 3000:3000
        platform: linux/x86_64
        working_dir: /frontend
        depends_on:
            - backend
        restart: always
        networks:
            - web-net
        volumes:
            - ./frontend/src:/frontend/src
            - /frontend/node_modules
    backend:
        container_name: app_backend
        build: ./backend
        ports:
            - 3001:3001
        platform: linux/x86_64
        working_dir: /backend
        restart: always
        networks:
            - web-net
        volumes:
            - ./backend/src:/backend/src
            - /backend/node_modules

volumes:
    data: {}
networks:
    web-net:
        name: web-net
