services:
    frontend:
        container_name: app_frontend
        build: ./frontend
        ports:
            - ${FRONTEND_PORT}:3000
        env_file:
            - .env
        platform: linux/x86_64
        working_dir: /frontend
        depends_on:
            - backend
        restart: always
        networks:
            - web-net
        volumes:
            - ./frontend/src:/frontend/src
            - /frontend/node_modules
    backend:
        container_name: app_backend
        build: ./backend
        ports:
            - ${BACKEND_PORT}:8080
        env_file:
            - .env
        platform: linux/x86_64
        working_dir: /backend
        restart: always
        networks:
            - web-net
        volumes:
            - ./backend/src:/backend/src
            - /backend/node_modules
        environment:
            - DB_HOST=mysql
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=app_db
    mysql:
        image: mysql:latest
        container_name: app_mysql
        restart: always
        networks:
            - web-net
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app_db
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:3306

volumes:
    data: {}
    mysql_data: {}
networks:
    web-net:
        name: web-net
